const WORDS_DATA = [
  {
    "spanish": "el perro",
    "type": "noun",
    "gender": "masculine",
    "italian": "cane",
    "german": "der Hund",
    "english": "dog",
    "symbol": "🐕",
    "sentence_es": "El **perro** corre en el parque.",
    "sentence_it": "Il **cane** corre nel parco.",
    "sentence_de": "Der **Hund** läuft im Park.",
    "sentence_en": "The **dog** runs in the park."
  },
  {
    "spanish": "la mujer",
    "type": "noun",
    "gender": "feminine",
    "italian": "donna",
    "german": "die Frau",
    "english": "woman",
    "symbol": "👩",
    "sentence_es": "La **mujer** lee un libro.",
    "sentence_it": "La **donna** legge un libro.",
    "sentence_de": "Die **Frau** liest ein Buch.",
    "sentence_en": "The **woman** reads a book."
  },
  {
    "spanish": "el chico",
    "type": "noun",
    "gender": "masculine",
    "italian": "ragazzo",
    "german": "der Junge",
    "english": "boy / guy",
    "symbol": "👦",
    "sentence_es": "El **chico** juega al fútbol.",
    "sentence_it": "Il **ragazzo** gioca a calcio.",
    "sentence_de": "Der **Junge** spielt Fußball.",
    "sentence_en": "The **boy** plays soccer."
  },
  {
    "spanish": "la chica",
    "type": "noun",
    "gender": "feminine",
    "italian": "ragazza",
    "german": "das Mädchen",
    "english": "girl",
    "symbol": "👧",
    "sentence_es": "La **chica** canta muy bien.",
    "sentence_it": "La **ragazza** canta molto bene.",
    "sentence_de": "Das **Mädchen** singt sehr gut.",
    "sentence_en": "The **girl** sings very well."
  },
  {
    "spanish": "el niño",
    "type": "noun",
    "gender": "masculine",
    "italian": "bambino",
    "german": "das Kind / der Junge",
    "english": "child / boy",
    "symbol": "🧒",
    "sentence_es": "El **niño** duerme en su cama.",
    "sentence_it": "Il **bambino** dorme nel suo letto.",
    "sentence_de": "Das **Kind** schläft in seinem Bett.",
    "sentence_en": "The **child** sleeps in his bed."
  },
  {
    "spanish": "la niña",
    "type": "noun",
    "gender": "feminine",
    "italian": "bambina",
    "german": "das Kind / das Mädchen",
    "english": "child / girl",
    "symbol": "👧",
    "sentence_es": "La **niña** dibuja una flor.",
    "sentence_it": "La **bambina** disegna un fiore.",
    "sentence_de": "Das **Mädchen** malt eine Blume.",
    "sentence_en": "The **girl** draws a flower."
  },
  {
    "spanish": "la espalda",
    "type": "noun",
    "gender": "feminine",
    "italian": "schiena",
    "german": "der Rücken",
    "english": "back (anatomy)",
    "symbol": "🔙",
    "sentence_es": "Me duele la **espalda**.",
    "sentence_it": "Mi fa male la **schiena**.",
    "sentence_de": "Mir tut der **Rücken** weh.",
    "sentence_en": "My **back** hurts."
  },
  {
    "spanish": "el hombro",
    "type": "noun",
    "gender": "masculine",
    "italian": "spalla",
    "german": "die Schulter",
    "english": "shoulder",
    "symbol": "💪",
    "sentence_es": "Llevo la mochila en el **hombro**.",
    "sentence_it": "Porto lo zaino sulla **spalla**.",
    "sentence_de": "Ich trage den Rucksack auf der **Schulter**.",
    "sentence_en": "I carry the backpack on my **shoulder**."
  },
  {
    "spanish": "la rodilla",
    "type": "noun",
    "gender": "feminine",
    "italian": "ginocchio",
    "german": "das Knie",
    "english": "knee",
    "symbol": "🦵",
    "sentence_es": "Me he lastimado la **rodilla**.",
    "sentence_it": "Mi sono fatto male al **ginocchio**.",
    "sentence_de": "Ich habe mir das **Knie** verletzt.",
    "sentence_en": "I hurt my **knee**."
  },
  {
    "spanish": "el tobillo",
    "type": "noun",
    "gender": "masculine",
    "italian": "caviglia",
    "german": "der Knöchel",
    "english": "ankle",
    "symbol": "🦶",
    "sentence_es": "Me torcí el **tobillo** corriendo.",
    "sentence_it": "Mi sono storto la **caviglia** correndo.",
    "sentence_de": "Ich habe mir beim Laufen den **Knöchel** verstaucht.",
    "sentence_en": "I twisted my **ankle** while running."
  },
  {
    "spanish": "la muñeca",
    "type": "noun",
    "gender": "feminine",
    "italian": "polso",
    "german": "das Handgelenk",
    "english": "wrist",
    "symbol": "🖐️",
    "sentence_es": "Llevo un reloj en la **muñeca**.",
    "sentence_it": "Porto un orologio al **polso**.",
    "sentence_de": "Ich trage eine Uhr am **Handgelenk**.",
    "sentence_en": "I wear a watch on my **wrist**."
  },
  {
    "spanish": "la barbilla",
    "type": "noun",
    "gender": "feminine",
    "italian": "mento",
    "german": "das Kinn",
    "english": "chin",
    "symbol": "🧔",
    "sentence_es": "Tiene un hoyuelo en la **barbilla**.",
    "sentence_it": "Ha una fossetta sul **mento**.",
    "sentence_de": "Er hat ein Grübchen am **Kinn**.",
    "sentence_en": "He has a dimple on his **chin**."
  },
  {
    "spanish": "la mejilla",
    "type": "noun",
    "gender": "feminine",
    "italian": "guancia",
    "german": "die Wange",
    "english": "cheek",
    "symbol": "😊",
    "sentence_es": "Le dio un beso en la **mejilla**.",
    "sentence_it": "Le ha dato un bacio sulla **guancia**.",
    "sentence_de": "Sie gab ihm einen Kuss auf die **Wange**.",
    "sentence_en": "She gave him a kiss on the **cheek**."
  },
  {
    "spanish": "la ceja",
    "type": "noun",
    "gender": "feminine",
    "italian": "sopracciglio",
    "german": "die Augenbraue",
    "english": "eyebrow",
    "symbol": "🤨",
    "sentence_es": "Se levantó una **ceja** sorprendido.",
    "sentence_it": "Ha alzato un **sopracciglio** sorpreso.",
    "sentence_de": "Er hob überrascht eine **Augenbraue**.",
    "sentence_en": "He raised an **eyebrow** in surprise."
  },
  {
    "spanish": "la pestaña",
    "type": "noun",
    "gender": "feminine",
    "italian": "ciglia",
    "german": "die Wimper",
    "english": "eyelash",
    "symbol": "👁️",
    "sentence_es": "Tiene las **pestañas** muy largas.",
    "sentence_it": "Ha le **ciglia** molto lunghe.",
    "sentence_de": "Sie hat sehr lange **Wimpern**.",
    "sentence_en": "She has very long **eyelashes**."
  },
  {
    "spanish": "el pájaro",
    "type": "noun",
    "gender": "masculine",
    "italian": "uccello",
    "german": "der Vogel",
    "english": "bird",
    "symbol": "🐦",
    "sentence_es": "El **pájaro** canta en el árbol.",
    "sentence_it": "L'**uccello** canta sull'albero.",
    "sentence_de": "Der **Vogel** singt auf dem Baum.",
    "sentence_en": "The **bird** sings in the tree."
  },
  {
    "spanish": "el ratón",
    "type": "noun",
    "gender": "masculine",
    "italian": "topo",
    "german": "die Maus",
    "english": "mouse",
    "symbol": "🐭",
    "sentence_es": "El **ratón** se esconde en la cocina.",
    "sentence_it": "Il **topo** si nasconde in cucina.",
    "sentence_de": "Die **Maus** versteckt sich in der Küche.",
    "sentence_en": "The **mouse** hides in the kitchen."
  },
  {
    "spanish": "el zorro",
    "type": "noun",
    "gender": "masculine",
    "italian": "volpe",
    "german": "der Fuchs",
    "english": "fox",
    "symbol": "🦊",
    "sentence_es": "El **zorro** corre por el bosque.",
    "sentence_it": "La **volpe** corre nel bosco.",
    "sentence_de": "Der **Fuchs** läuft durch den Wald.",
    "sentence_en": "The **fox** runs through the forest."
  },
  {
    "spanish": "la mariposa",
    "type": "noun",
    "gender": "feminine",
    "italian": "farfalla",
    "german": "der Schmetterling",
    "english": "butterfly",
    "symbol": "🦋",
    "sentence_es": "Una **mariposa** vuela sobre las flores.",
    "sentence_it": "Una **farfalla** vola sui fiori.",
    "sentence_de": "Ein **Schmetterling** fliegt über die Blumen.",
    "sentence_en": "A **butterfly** flies over the flowers."
  },
  {
    "spanish": "el coche",
    "type": "noun",
    "gender": "masculine",
    "italian": "macchina",
    "german": "das Auto / der Wagen",
    "english": "car",
    "symbol": "🚗",
    "sentence_es": "El **coche** está aparcado en la calle.",
    "sentence_it": "La **macchina** è parcheggiata in strada.",
    "sentence_de": "Das **Auto** ist auf der Straße geparkt.",
    "sentence_en": "The **car** is parked on the street."
  },
  {
    "spanish": "la mesa",
    "type": "noun",
    "gender": "feminine",
    "italian": "tavolo",
    "german": "der Tisch",
    "english": "table",
    "symbol": "🪑",
    "sentence_es": "Ponemos los platos en la **mesa**.",
    "sentence_it": "Mettiamo i piatti sul **tavolo**.",
    "sentence_de": "Wir stellen die Teller auf den **Tisch**.",
    "sentence_en": "We put the plates on the **table**."
  },
  {
    "spanish": "la cama",
    "type": "noun",
    "gender": "feminine",
    "italian": "letto",
    "german": "das Bett",
    "english": "bed",
    "symbol": "🛏️",
    "sentence_es": "Me acuesto en la **cama** temprano.",
    "sentence_it": "Mi corico nel **letto** presto.",
    "sentence_de": "Ich gehe früh ins **Bett**.",
    "sentence_en": "I go to **bed** early."
  },
  {
    "spanish": "la silla",
    "type": "noun",
    "gender": "feminine",
    "italian": "sedia",
    "german": "der Stuhl",
    "english": "chair",
    "symbol": "🪑",
    "sentence_es": "Siéntate en esa **silla**.",
    "sentence_it": "Siediti su quella **sedia**.",
    "sentence_de": "Setz dich auf diesen **Stuhl**.",
    "sentence_en": "Sit on that **chair**."
  },
  {
    "spanish": "la ventana",
    "type": "noun",
    "gender": "feminine",
    "italian": "finestra",
    "german": "das Fenster",
    "english": "window",
    "symbol": "🪟",
    "sentence_es": "Abro la **ventana** para que entre aire.",
    "sentence_it": "Apro la **finestra** per far entrare aria.",
    "sentence_de": "Ich öffne das **Fenster**, damit Luft hereinkommt.",
    "sentence_en": "I open the **window** to let air in."
  },
  {
    "spanish": "el techo",
    "type": "noun",
    "gender": "masculine",
    "italian": "soffitto",
    "german": "die Decke (Zimmerdecke)",
    "english": "ceiling",
    "symbol": "🏠",
    "sentence_es": "Hay una mancha en el **techo**.",
    "sentence_it": "C'è una macchia sul **soffitto**.",
    "sentence_de": "Es gibt einen Fleck an der **Decke**.",
    "sentence_en": "There is a stain on the **ceiling**."
  },
  {
    "spanish": "el suelo",
    "type": "noun",
    "gender": "masculine",
    "italian": "pavimento",
    "german": "der Boden / der Fußboden",
    "english": "floor / ground",
    "symbol": "🪵",
    "sentence_es": "El juguete cayó al **suelo**.",
    "sentence_it": "Il giocattolo è caduto sul **pavimento**.",
    "sentence_de": "Das Spielzeug fiel auf den **Boden**.",
    "sentence_en": "The toy fell on the **floor**."
  },
  {
    "spanish": "la pared",
    "type": "noun",
    "gender": "feminine",
    "italian": "muro",
    "german": "die Wand",
    "english": "wall",
    "symbol": "🧱",
    "sentence_es": "Colgamos un cuadro en la **pared**.",
    "sentence_it": "Appendiamo un quadro al **muro**.",
    "sentence_de": "Wir hängen ein Bild an die **Wand**.",
    "sentence_en": "We hang a picture on the **wall**."
  },
  {
    "spanish": "la tienda",
    "type": "noun",
    "gender": "feminine",
    "italian": "negozio",
    "german": "der Laden / das Geschäft",
    "english": "shop / store",
    "symbol": "🏬",
    "sentence_es": "Compramos pan en la **tienda**.",
    "sentence_it": "Compriamo il pane al **negozio**.",
    "sentence_de": "Wir kaufen Brot im **Laden**.",
    "sentence_en": "We buy bread at the **store**."
  },
  {
    "spanish": "el barrio",
    "type": "noun",
    "gender": "masculine",
    "italian": "quartiere",
    "german": "das Stadtviertel / das Viertel",
    "english": "neighborhood / district",
    "symbol": "🏘️",
    "sentence_es": "Vivimos en un **barrio** tranquilo.",
    "sentence_it": "Viviamo in un **quartiere** tranquillo.",
    "sentence_de": "Wir wohnen in einem ruhigen **Viertel**.",
    "sentence_en": "We live in a quiet **neighborhood**."
  },
  {
    "spanish": "la acera",
    "type": "noun",
    "gender": "feminine",
    "italian": "marciapiede",
    "german": "der Gehweg / der Bürgersteig",
    "english": "sidewalk / pavement",
    "symbol": "🚶",
    "sentence_es": "Caminamos por la **acera**.",
    "sentence_it": "Camminiamo sul **marciapiede**.",
    "sentence_de": "Wir gehen auf dem **Bürgersteig**.",
    "sentence_en": "We walk on the **sidewalk**."
  },
  {
    "spanish": "la esquina",
    "type": "noun",
    "gender": "feminine",
    "italian": "angolo",
    "german": "die Straßenecke",
    "english": "street corner",
    "symbol": "📐",
    "sentence_es": "El coche giró en la **esquina**.",
    "sentence_it": "L'auto ha girato all'**angolo**.",
    "sentence_de": "Das Auto bog an der **Ecke** ab.",
    "sentence_en": "The car turned at the **corner**."
  },
  {
    "spanish": "el rincón",
    "type": "noun",
    "gender": "masculine",
    "italian": "angolo",
    "german": "die Innenecke / der Winkel",
    "english": "corner (interior)",
    "symbol": "📐",
    "sentence_es": "Puso la lámpara en el **rincón**.",
    "sentence_it": "Ha messo la lampada nell'**angolo**.",
    "sentence_de": "Er stellte die Lampe in die **Ecke**.",
    "sentence_en": "He put the lamp in the **corner**."
  },
  {
    "spanish": "el bolsillo",
    "type": "noun",
    "gender": "masculine",
    "italian": "tasca",
    "german": "die Tasche (Hosentasche)",
    "english": "pocket",
    "symbol": "👖",
    "sentence_es": "Guardo las llaves en el **bolsillo**.",
    "sentence_it": "Metto le chiavi in **tasca**.",
    "sentence_de": "Ich stecke die Schlüssel in die **Tasche**.",
    "sentence_en": "I keep the keys in my **pocket**."
  },
  {
    "spanish": "la falda",
    "type": "noun",
    "gender": "feminine",
    "italian": "gonna",
    "german": "der Rock",
    "english": "skirt",
    "symbol": "👗",
    "sentence_es": "Lleva una **falda** azul.",
    "sentence_it": "Indossa una **gonna** blu.",
    "sentence_de": "Sie trägt einen blauen **Rock**.",
    "sentence_en": "She wears a blue **skirt**."
  },
  {
    "spanish": "el sombrero",
    "type": "noun",
    "gender": "masculine",
    "italian": "cappello",
    "german": "der Hut",
    "english": "hat",
    "symbol": "👒",
    "sentence_es": "Se puso el **sombrero** para el sol.",
    "sentence_it": "Si è messo il **cappello** per il sole.",
    "sentence_de": "Er setzte den **Hut** wegen der Sonne auf.",
    "sentence_en": "He put on his **hat** because of the sun."
  },
  {
    "spanish": "el abrigo",
    "type": "noun",
    "gender": "masculine",
    "italian": "cappotto",
    "german": "der Mantel",
    "english": "coat / overcoat",
    "symbol": "🧥",
    "sentence_es": "Hace frío, ponte el **abrigo**.",
    "sentence_it": "Fa freddo, mettiti il **cappotto**.",
    "sentence_de": "Es ist kalt, zieh den **Mantel** an.",
    "sentence_en": "It's cold, put on your **coat**."
  },
  {
    "spanish": "los zapatos",
    "type": "noun",
    "gender": "masculine (plural)",
    "italian": "scarpe",
    "german": "die Schuhe",
    "english": "shoes",
    "symbol": "👞",
    "sentence_es": "Me compré unos **zapatos** nuevos.",
    "sentence_it": "Mi sono comprato delle **scarpe** nuove.",
    "sentence_de": "Ich habe mir neue **Schuhe** gekauft.",
    "sentence_en": "I bought new **shoes**."
  },
  {
    "spanish": "las gafas",
    "type": "noun",
    "gender": "feminine (plural)",
    "italian": "occhiali",
    "german": "die Brille",
    "english": "glasses / spectacles",
    "symbol": "👓",
    "sentence_es": "Necesito mis **gafas** para leer.",
    "sentence_it": "Ho bisogno dei miei **occhiali** per leggere.",
    "sentence_de": "Ich brauche meine **Brille** zum Lesen.",
    "sentence_en": "I need my **glasses** to read."
  },
  {
    "spanish": "la toalla",
    "type": "noun",
    "gender": "feminine",
    "italian": "asciugamano",
    "german": "das Handtuch",
    "english": "towel",
    "symbol": "🧖",
    "sentence_es": "Sécate con la **toalla**.",
    "sentence_it": "Asciugati con l'**asciugamano**.",
    "sentence_de": "Trockne dich mit dem **Handtuch** ab.",
    "sentence_en": "Dry yourself with the **towel**."
  },
  {
    "spanish": "el paraguas",
    "type": "noun",
    "gender": "masculine",
    "italian": "ombrello",
    "german": "der Regenschirm",
    "english": "umbrella",
    "symbol": "☂️",
    "sentence_es": "Llueve, coge el **paraguas**.",
    "sentence_it": "Piove, prendi l'**ombrello**.",
    "sentence_de": "Es regnet, nimm den **Regenschirm**.",
    "sentence_en": "It's raining, take the **umbrella**."
  },
  {
    "spanish": "el vaso",
    "type": "noun",
    "gender": "masculine",
    "italian": "bicchiere",
    "german": "das Trinkglas",
    "english": "drinking glass",
    "symbol": "🥛",
    "sentence_es": "Bebo agua de un **vaso**.",
    "sentence_it": "Bevo acqua da un **bicchiere**.",
    "sentence_de": "Ich trinke Wasser aus einem **Glas**.",
    "sentence_en": "I drink water from a **glass**."
  },
  {
    "spanish": "el tenedor",
    "type": "noun",
    "gender": "masculine",
    "italian": "forchetta",
    "german": "die Gabel",
    "english": "fork",
    "symbol": "🍴",
    "sentence_es": "Como la pasta con un **tenedor**.",
    "sentence_it": "Mangio la pasta con una **forchetta**.",
    "sentence_de": "Ich esse die Pasta mit einer **Gabel**.",
    "sentence_en": "I eat the pasta with a **fork**."
  },
  {
    "spanish": "la cuchara",
    "type": "noun",
    "gender": "feminine",
    "italian": "cucchiaio",
    "german": "der Löffel",
    "english": "spoon",
    "symbol": "🥄",
    "sentence_es": "Remuevo el café con una **cuchara**.",
    "sentence_it": "Mescolo il caffè con un **cucchiaio**.",
    "sentence_de": "Ich rühre den Kaffee mit einem **Löffel** um.",
    "sentence_en": "I stir the coffee with a **spoon**."
  },
  {
    "spanish": "el cuchillo",
    "type": "noun",
    "gender": "masculine",
    "italian": "coltello",
    "german": "das Messer",
    "english": "knife",
    "symbol": "🔪",
    "sentence_es": "Corto el pan con un **cuchillo**.",
    "sentence_it": "Taglio il pane con un **coltello**.",
    "sentence_de": "Ich schneide das Brot mit einem **Messer**.",
    "sentence_en": "I cut the bread with a **knife**."
  },
  {
    "spanish": "el desayuno",
    "type": "noun",
    "gender": "masculine",
    "italian": "colazione",
    "german": "das Frühstück",
    "english": "breakfast",
    "symbol": "🍳",
    "sentence_es": "Tomamos el **desayuno** a las ocho.",
    "sentence_it": "Facciamo **colazione** alle otto.",
    "sentence_de": "Wir essen um acht Uhr **Frühstück**.",
    "sentence_en": "We have **breakfast** at eight."
  },
  {
    "spanish": "el almuerzo",
    "type": "noun",
    "gender": "masculine",
    "italian": "pranzo",
    "german": "das Mittagessen",
    "english": "lunch",
    "symbol": "🍱",
    "sentence_es": "El **almuerzo** está listo.",
    "sentence_it": "Il **pranzo** è pronto.",
    "sentence_de": "Das **Mittagessen** ist fertig.",
    "sentence_en": "**Lunch** is ready."
  },
  {
    "spanish": "el aceite",
    "type": "noun",
    "gender": "masculine",
    "italian": "olio",
    "german": "das Öl",
    "english": "oil (cooking / olive)",
    "symbol": "🫒",
    "sentence_es": "Añade **aceite** a la sartén.",
    "sentence_it": "Aggiungi l'**olio** alla padella.",
    "sentence_de": "Gib **Öl** in die Pfanne.",
    "sentence_en": "Add **oil** to the pan."
  },
  {
    "spanish": "la mantequilla",
    "type": "noun",
    "gender": "feminine",
    "italian": "burro",
    "german": "die Butter",
    "english": "butter",
    "symbol": "🧈",
    "sentence_es": "Unto pan con **mantequilla**.",
    "sentence_it": "Spalmo il pane con il **burro**.",
    "sentence_de": "Ich streiche Brot mit **Butter**.",
    "sentence_en": "I spread bread with **butter**."
  },
  {
    "spanish": "el queso",
    "type": "noun",
    "gender": "masculine",
    "italian": "formaggio",
    "german": "der Käse",
    "english": "cheese",
    "symbol": "🧀",
    "sentence_es": "Me gusta el **queso** con pan.",
    "sentence_it": "Mi piace il **formaggio** con il pane.",
    "sentence_de": "Ich mag **Käse** mit Brot.",
    "sentence_en": "I like **cheese** with bread."
  },
  {
    "spanish": "la fresa",
    "type": "noun",
    "gender": "feminine",
    "italian": "fragola",
    "german": "die Erdbeere",
    "english": "strawberry",
    "symbol": "🍓",
    "sentence_es": "Como una **fresa** dulce.",
    "sentence_it": "Mangio una **fragola** dolce.",
    "sentence_de": "Ich esse eine süße **Erdbeere**.",
    "sentence_en": "I eat a sweet **strawberry**."
  },
  {
    "spanish": "la manzana",
    "type": "noun",
    "gender": "feminine",
    "italian": "mela",
    "german": "der Apfel",
    "english": "apple",
    "symbol": "🍎",
    "sentence_es": "Como una **manzana** cada día.",
    "sentence_it": "Mangio una **mela** ogni giorno.",
    "sentence_de": "Ich esse jeden Tag einen **Apfel**.",
    "sentence_en": "I eat an **apple** every day."
  },
  {
    "spanish": "la madera",
    "type": "noun",
    "gender": "feminine",
    "italian": "legno",
    "german": "das Holz",
    "english": "wood",
    "symbol": "🪵",
    "sentence_es": "La mesa es de **madera**.",
    "sentence_it": "Il tavolo è di **legno**.",
    "sentence_de": "Der Tisch ist aus **Holz**.",
    "sentence_en": "The table is made of **wood**."
  },
  {
    "spanish": "la madrugada",
    "type": "noun",
    "gender": "feminine",
    "italian": "alba",
    "german": "das Morgengrauen / die Frühe",
    "english": "dawn / early morning",
    "symbol": "🌅",
    "sentence_es": "Llegamos a casa de **madrugada**.",
    "sentence_it": "Torniamo a casa all'**alba**.",
    "sentence_de": "Wir kamen im **Morgengrauen** nach Hause.",
    "sentence_en": "We got home at **dawn**."
  },
  {
    "spanish": "la pesadilla",
    "type": "noun",
    "gender": "feminine",
    "italian": "incubo",
    "german": "der Albtraum",
    "english": "nightmare",
    "symbol": "😱",
    "sentence_es": "Tuve una **pesadilla** horrible.",
    "sentence_it": "Ho fatto un **incubo** orribile.",
    "sentence_de": "Ich hatte einen schrecklichen **Albtraum**.",
    "sentence_en": "I had a terrible **nightmare**."
  },
  {
    "spanish": "el miedo",
    "type": "noun",
    "gender": "masculine",
    "italian": "paura",
    "german": "die Angst",
    "english": "fear",
    "symbol": "😨",
    "sentence_es": "Tengo **miedo** de la oscuridad.",
    "sentence_it": "Ho **paura** del buio.",
    "sentence_de": "Ich habe **Angst** vor der Dunkelheit.",
    "sentence_en": "I have a **fear** of the dark."
  },
  {
    "spanish": "el juguete",
    "type": "noun",
    "gender": "masculine",
    "italian": "giocattolo",
    "german": "das Spielzeug",
    "english": "toy",
    "symbol": "🧸",
    "sentence_es": "El niño rompió su **juguete**.",
    "sentence_it": "Il bambino ha rotto il suo **giocattolo**.",
    "sentence_de": "Das Kind hat sein **Spielzeug** kaputt gemacht.",
    "sentence_en": "The child broke his **toy**."
  },
  {
    "spanish": "el charco",
    "type": "noun",
    "gender": "masculine",
    "italian": "pozzanghera",
    "german": "die Pfütze",
    "english": "puddle",
    "symbol": "💧",
    "sentence_es": "El perro salta en el **charco**.",
    "sentence_it": "Il cane salta nella **pozzanghera**.",
    "sentence_de": "Der Hund springt in die **Pfütze**.",
    "sentence_en": "The dog jumps in the **puddle**."
  },
  {
    "spanish": "la ola",
    "type": "noun",
    "gender": "feminine",
    "italian": "onda",
    "german": "die Welle",
    "english": "wave",
    "symbol": "🌊",
    "sentence_es": "Una **ola** grande llegó a la playa.",
    "sentence_it": "Un'**onda** grande è arrivata sulla spiaggia.",
    "sentence_de": "Eine große **Welle** erreichte den Strand.",
    "sentence_en": "A big **wave** reached the beach."
  },
  {
    "spanish": "la nube",
    "type": "noun",
    "gender": "feminine",
    "italian": "nuvola",
    "german": "die Wolke",
    "english": "cloud",
    "symbol": "☁️",
    "sentence_es": "Una **nube** blanca cruza el cielo.",
    "sentence_it": "Una **nuvola** bianca attraversa il cielo.",
    "sentence_de": "Eine weiße **Wolke** zieht über den Himmel.",
    "sentence_en": "A white **cloud** crosses the sky."
  },
  {
    "spanish": "la lluvia",
    "type": "noun",
    "gender": "feminine",
    "italian": "pioggia",
    "german": "der Regen",
    "english": "rain",
    "symbol": "🌧️",
    "sentence_es": "La **lluvia** cae sobre la ciudad.",
    "sentence_it": "La **pioggia** cade sulla città.",
    "sentence_de": "Der **Regen** fällt auf die Stadt.",
    "sentence_en": "The **rain** falls on the city."
  },
  {
    "spanish": "el relámpago",
    "type": "noun",
    "gender": "masculine",
    "italian": "fulmine",
    "german": "der Blitz",
    "english": "lightning",
    "symbol": "⚡",
    "sentence_es": "Un **relámpago** iluminó el cielo.",
    "sentence_it": "Un **fulmine** ha illuminato il cielo.",
    "sentence_de": "Ein **Blitz** erhellte den Himmel.",
    "sentence_en": "A bolt of **lightning** lit up the sky."
  },
  {
    "spanish": "la huella",
    "type": "noun",
    "gender": "feminine",
    "italian": "impronta",
    "german": "die Spur / der Fußabdruck",
    "english": "footprint / track / trace",
    "symbol": "👣",
    "sentence_es": "Dejó una **huella** en la arena.",
    "sentence_it": "Ha lasciato un'**impronta** nella sabbia.",
    "sentence_de": "Er hinterließ einen **Fußabdruck** im Sand.",
    "sentence_en": "He left a **footprint** in the sand."
  },
  {
    "spanish": "la basura",
    "type": "noun",
    "gender": "feminine",
    "italian": "spazzatura",
    "german": "der Müll / der Abfall",
    "english": "trash / rubbish",
    "symbol": "🗑️",
    "sentence_es": "Saco la **basura** todas las noches.",
    "sentence_it": "Butto la **spazzatura** ogni sera.",
    "sentence_de": "Ich bringe jeden Abend den **Müll** raus.",
    "sentence_en": "I take out the **trash** every evening."
  },
  {
    "spanish": "la añoranza",
    "type": "noun",
    "gender": "feminine",
    "italian": "nostalgia",
    "german": "die Sehnsucht / die Wehmut",
    "english": "yearning / longing",
    "symbol": "💭",
    "sentence_es": "Siente **añoranza** de su país.",
    "sentence_it": "Prova **nostalgia** per il suo paese.",
    "sentence_de": "Er verspürt **Sehnsucht** nach seinem Land.",
    "sentence_en": "He feels a **yearning** for his country."
  },
  {
    "spanish": "el hábito",
    "type": "noun",
    "gender": "masculine",
    "italian": "abitudine",
    "german": "die Gewohnheit",
    "english": "habit",
    "symbol": "🔄",
    "sentence_es": "Leer antes de dormir es un buen **hábito**.",
    "sentence_it": "Leggere prima di dormire è una buona **abitudine**.",
    "sentence_de": "Vor dem Schlafen zu lesen ist eine gute **Gewohnheit**.",
    "sentence_en": "Reading before bed is a good **habit**."
  },
  {
    "spanish": "el cumpleaños",
    "type": "noun",
    "gender": "masculine",
    "italian": "compleanno",
    "german": "der Geburtstag",
    "english": "birthday",
    "symbol": "🎂",
    "sentence_es": "Hoy es mi **cumpleaños**.",
    "sentence_it": "Oggi è il mio **compleanno**.",
    "sentence_de": "Heute ist mein **Geburtstag**.",
    "sentence_en": "Today is my **birthday**."
  },
  {
    "spanish": "el sueño",
    "type": "noun",
    "gender": "masculine",
    "italian": "sonno",
    "german": "der Schlaf / die Müdigkeit",
    "english": "sleep / sleepiness",
    "symbol": "💤",
    "sentence_es": "Tengo mucho **sueño** esta noche.",
    "sentence_it": "Ho molto **sonno** stanotte.",
    "sentence_de": "Ich brauche heute Abend viel **Schlaf**.",
    "sentence_en": "I need a lot of **sleep** tonight."
  },
  {
    "spanish": "la rebanada",
    "type": "noun",
    "gender": "feminine",
    "italian": "fetta",
    "german": "die Scheibe (Brot)",
    "english": "slice",
    "symbol": "🍞",
    "sentence_es": "Corta una **rebanada** de pan.",
    "sentence_it": "Taglia una **fetta** di pane.",
    "sentence_de": "Schneide eine **Scheibe** Brot.",
    "sentence_en": "Cut a **slice** of bread."
  },
  {
    "spanish": "la sartén",
    "type": "noun",
    "gender": "feminine",
    "italian": "padella",
    "german": "die Bratpfanne",
    "english": "frying pan",
    "symbol": "🍳",
    "sentence_es": "Frío los huevos en la **sartén**.",
    "sentence_it": "Friggo le uova nella **padella**.",
    "sentence_de": "Ich brate die Eier in der **Bratpfanne**.",
    "sentence_en": "I fry the eggs in the **frying pan**."
  },
  {
    "spanish": "las tijeras",
    "type": "noun",
    "gender": "feminine (plural)",
    "italian": "forbici",
    "german": "die Schere",
    "english": "scissors",
    "symbol": "✂️",
    "sentence_es": "Corto el papel con las **tijeras**.",
    "sentence_it": "Taglio la carta con le **forbici**.",
    "sentence_de": "Ich schneide das Papier mit der **Schere**.",
    "sentence_en": "I cut the paper with the **scissors**."
  },
  {
    "spanish": "los cubiertos",
    "type": "noun",
    "gender": "masculine (plural)",
    "italian": "posate",
    "german": "das Besteck",
    "english": "cutlery / silverware",
    "symbol": "🍴",
    "sentence_es": "Pon los **cubiertos** en la mesa.",
    "sentence_it": "Metti le **posate** in tavola.",
    "sentence_de": "Leg das **Besteck** auf den Tisch.",
    "sentence_en": "Put the **cutlery** on the table."
  },
  {
    "spanish": "el estante",
    "type": "noun",
    "gender": "masculine",
    "italian": "scaffale",
    "german": "das Regal",
    "english": "shelf",
    "symbol": "📚",
    "sentence_es": "Los libros están en el **estante**.",
    "sentence_it": "I libri sono sullo **scaffale**.",
    "sentence_de": "Die Bücher stehen im **Regal**.",
    "sentence_en": "The books are on the **shelf**."
  },
  {
    "spanish": "el cajón",
    "type": "noun",
    "gender": "masculine",
    "italian": "cassetto",
    "german": "die Schublade",
    "english": "drawer",
    "symbol": "🗄️",
    "sentence_es": "Guardo los calcetines en el **cajón**.",
    "sentence_it": "Metto i calzini nel **cassetto**.",
    "sentence_de": "Ich lege die Socken in die **Schublade**.",
    "sentence_en": "I put the socks in the **drawer**."
  },
  {
    "spanish": "la almohada",
    "type": "noun",
    "gender": "feminine",
    "italian": "cuscino",
    "german": "das Kopfkissen",
    "english": "pillow",
    "symbol": "🛌",
    "sentence_es": "Apoyo la cabeza en la **almohada**.",
    "sentence_it": "Appoggio la testa sul **cuscino**.",
    "sentence_de": "Ich lege den Kopf auf das **Kopfkissen**.",
    "sentence_en": "I rest my head on the **pillow**."
  },
  {
    "spanish": "la manta",
    "type": "noun",
    "gender": "feminine",
    "italian": "coperta",
    "german": "die Decke (Wohndecke)",
    "english": "blanket",
    "symbol": "🛋️",
    "sentence_es": "Me tapo con una **manta** caliente.",
    "sentence_it": "Mi copro con una **coperta** calda.",
    "sentence_de": "Ich decke mich mit einer warmen **Decke** zu.",
    "sentence_en": "I cover myself with a warm **blanket**."
  },
  {
    "spanish": "la sábana",
    "type": "noun",
    "gender": "feminine",
    "italian": "lenzuolo",
    "german": "das Bettlaken",
    "english": "bed sheet",
    "symbol": "🛏️",
    "sentence_es": "Cambio las **sábanas** de la cama.",
    "sentence_it": "Cambio le **lenzuola** del letto.",
    "sentence_de": "Ich wechsle die **Bettlaken**.",
    "sentence_en": "I change the **bed sheets**."
  },
  {
    "spanish": "el grifo",
    "type": "noun",
    "gender": "masculine",
    "italian": "rubinetto",
    "german": "der Wasserhahn",
    "english": "tap / faucet",
    "symbol": "🚰",
    "sentence_es": "Cierra el **grifo** del agua.",
    "sentence_it": "Chiudi il **rubinetto** dell'acqua.",
    "sentence_de": "Dreh den **Wasserhahn** zu.",
    "sentence_en": "Turn off the **tap**."
  },
  {
    "spanish": "el peine",
    "type": "noun",
    "gender": "masculine",
    "italian": "pettine",
    "german": "der Kamm",
    "english": "comb",
    "symbol": "🪮",
    "sentence_es": "Se peina con un **peine**.",
    "sentence_it": "Si pettina con un **pettine**.",
    "sentence_de": "Er kämmt sich mit einem **Kamm**.",
    "sentence_en": "He combs his hair with a **comb**."
  },
  {
    "spanish": "el cepillo",
    "type": "noun",
    "gender": "masculine",
    "italian": "spazzola",
    "german": "die Bürste",
    "english": "brush",
    "symbol": "🪥",
    "sentence_es": "Limpio el pelo con un **cepillo**.",
    "sentence_it": "Pulisco i capelli con una **spazzola**.",
    "sentence_de": "Ich bürste die Haare mit einer **Bürste**.",
    "sentence_en": "I brush my hair with a **brush**."
  },
  {
    "spanish": "los calcetines",
    "type": "noun",
    "gender": "masculine (plural)",
    "italian": "calzini",
    "german": "die Socken",
    "english": "socks",
    "symbol": "🧦",
    "sentence_es": "Me pongo los **calcetines** por la mañana.",
    "sentence_it": "Mi metto i **calzini** al mattino.",
    "sentence_de": "Ich ziehe morgens die **Socken** an.",
    "sentence_en": "I put on my **socks** in the morning."
  },
  {
    "spanish": "el cinturón",
    "type": "noun",
    "gender": "masculine",
    "italian": "cintura",
    "german": "der Gürtel",
    "english": "belt",
    "symbol": "🥋",
    "sentence_es": "Lleva un **cinturón** de cuero.",
    "sentence_it": "Indossa una **cintura** di cuoio.",
    "sentence_de": "Er trägt einen ledernen **Gürtel**.",
    "sentence_en": "He wears a leather **belt**."
  },
  {
    "spanish": "el albornoz",
    "type": "noun",
    "gender": "masculine",
    "italian": "accappatoio",
    "german": "der Bademantel",
    "english": "bathrobe",
    "symbol": "👘",
    "sentence_es": "Salgo de la ducha con el **albornoz**.",
    "sentence_it": "Esco dalla doccia con l'**accappatoio**.",
    "sentence_de": "Ich komme mit dem **Bademantel** aus der Dusche.",
    "sentence_en": "I come out of the shower in my **bathrobe**."
  },
  {
    "spanish": "la billetera",
    "type": "noun",
    "gender": "feminine",
    "italian": "portafoglio",
    "german": "die Brieftasche / das Portemonnaie",
    "english": "wallet",
    "symbol": "👛",
    "sentence_es": "Guardo el dinero en la **billetera**.",
    "sentence_it": "Metto i soldi nel **portafoglio**.",
    "sentence_de": "Ich bewahre das Geld in der **Brieftasche** auf.",
    "sentence_en": "I keep the money in my **wallet**."
  },
  {
    "spanish": "el paraguero",
    "type": "noun",
    "gender": "masculine",
    "italian": "portaombrelli",
    "german": "der Schirmständer",
    "english": "umbrella stand",
    "symbol": "🌂",
    "sentence_es": "Deja el paraguas en el **paraguero**.",
    "sentence_it": "Lascia l'ombrello nel **portaombrelli**.",
    "sentence_de": "Stell den Regenschirm in den **Schirmständer**.",
    "sentence_en": "Put the umbrella in the **umbrella stand**."
  },
  {
    "spanish": "el rebaño",
    "type": "noun",
    "gender": "masculine",
    "italian": "gregge",
    "german": "die Herde",
    "english": "flock / herd",
    "symbol": "🐑",
    "sentence_es": "El pastor cuida el **rebaño** de ovejas.",
    "sentence_it": "Il pastore accudisce il **gregge** di pecore.",
    "sentence_de": "Der Hirte hütet die **Herde** Schafe.",
    "sentence_en": "The shepherd looks after the **flock** of sheep."
  },
  {
    "spanish": "el trueno",
    "type": "noun",
    "gender": "masculine",
    "italian": "tuono",
    "german": "der Donner",
    "english": "thunder",
    "symbol": "🌩️",
    "sentence_es": "Se oyó un **trueno** fuerte.",
    "sentence_it": "Si è sentito un **tuono** forte.",
    "sentence_de": "Man hörte einen lauten **Donner**.",
    "sentence_en": "A loud clap of **thunder** was heard."
  },
  {
    "spanish": "el espejo",
    "type": "noun",
    "gender": "masculine",
    "italian": "specchio",
    "german": "der Spiegel",
    "english": "mirror",
    "symbol": "🪞",
    "sentence_es": "Me miro en el **espejo**.",
    "sentence_it": "Mi guardo allo **specchio**.",
    "sentence_de": "Ich schaue mich im **Spiegel** an.",
    "sentence_en": "I look at myself in the **mirror**."
  },
  {
    "spanish": "el hielo",
    "type": "noun",
    "gender": "masculine",
    "italian": "ghiaccio",
    "german": "das Eis",
    "english": "ice",
    "symbol": "🧊",
    "sentence_es": "Pon **hielo** en la bebida.",
    "sentence_it": "Metti il **ghiaccio** nella bevanda.",
    "sentence_de": "Gib **Eis** in das Getränk.",
    "sentence_en": "Put **ice** in the drink."
  },
  {
    "spanish": "el hierro",
    "type": "noun",
    "gender": "masculine",
    "italian": "ferro",
    "german": "das Eisen",
    "english": "iron",
    "symbol": "⛓️",
    "sentence_es": "La puerta es de **hierro**.",
    "sentence_it": "La porta è di **ferro**.",
    "sentence_de": "Die Tür ist aus **Eisen**.",
    "sentence_en": "The door is made of **iron**."
  },
  {
    "spanish": "la plata",
    "type": "noun",
    "gender": "feminine",
    "italian": "argento",
    "german": "das Silber",
    "english": "silver",
    "symbol": "🥈",
    "sentence_es": "El anillo es de **plata**.",
    "sentence_it": "L'anello è d'**argento**.",
    "sentence_de": "Der Ring ist aus **Silber**.",
    "sentence_en": "The ring is made of **silver**."
  },
  {
    "spanish": "hablar",
    "type": "verb",
    "gender": "-",
    "italian": "parlare",
    "german": "sprechen / reden",
    "english": "to speak / to talk",
    "symbol": "🗣️",
    "sentence_es": "Ella **habla** español muy bien.",
    "sentence_it": "Lei **parla** spagnolo molto bene.",
    "sentence_de": "Sie **spricht** sehr gut Spanisch.",
    "sentence_en": "She **speaks** Spanish very well."
  },
  {
    "spanish": "encontrar",
    "type": "verb",
    "gender": "-",
    "italian": "trovare",
    "german": "finden",
    "english": "to find / to meet",
    "symbol": "🔎",
    "sentence_es": "No **encuentro** mis llaves.",
    "sentence_it": "Non **trovo** le mie chiavi.",
    "sentence_de": "Ich **finde** meine Schlüssel nicht.",
    "sentence_en": "I can't **find** my keys."
  },
  {
    "spanish": "buscar",
    "type": "verb",
    "gender": "-",
    "italian": "cercare",
    "german": "suchen",
    "english": "to look for / to search",
    "symbol": "🔍",
    "sentence_es": "**Busco** trabajo nuevo.",
    "sentence_it": "**Cerco** un nuovo lavoro.",
    "sentence_de": "Ich **suche** eine neue Arbeit.",
    "sentence_en": "I **search** for a new job."
  },
  {
    "spanish": "llegar",
    "type": "verb",
    "gender": "-",
    "italian": "arrivare",
    "german": "ankommen",
    "english": "to arrive",
    "symbol": "🏁",
    "sentence_es": "El tren **llega** a las nueve.",
    "sentence_it": "Il treno **arriva** alle nove.",
    "sentence_de": "Der Zug **kommt** um neun Uhr **an**.",
    "sentence_en": "The train **arrives** at nine."
  },
  {
    "spanish": "salir",
    "type": "verb",
    "gender": "-",
    "italian": "uscire",
    "german": "hinausgehen / verlassen",
    "english": "to exit / to leave / to go out",
    "symbol": "🚪",
    "sentence_es": "**Salgo** de casa a las ocho.",
    "sentence_it": "**Esco** di casa alle otto.",
    "sentence_de": "Ich **verlasse** das Haus um acht Uhr.",
    "sentence_en": "I **leave** the house at eight."
  },
  {
    "spanish": "quedarse",
    "type": "verb",
    "gender": "-",
    "italian": "rimanere",
    "german": "bleiben",
    "english": "to stay / to remain",
    "symbol": "🛑",
    "sentence_es": "Me **quedo** en casa hoy.",
    "sentence_it": "**Rimango** a casa oggi.",
    "sentence_de": "Ich **bleibe** heute zu Hause.",
    "sentence_en": "I **stay** home today."
  },
  {
    "spanish": "olvidar",
    "type": "verb",
    "gender": "-",
    "italian": "dimenticare",
    "german": "vergessen",
    "english": "to forget",
    "symbol": "❓",
    "sentence_es": "Siempre **olvido** su nombre.",
    "sentence_it": "**Dimentico** sempre il suo nome.",
    "sentence_de": "Ich **vergesse** immer seinen Namen.",
    "sentence_en": "I always **forget** his name."
  },
  {
    "spanish": "mirar",
    "type": "verb",
    "gender": "-",
    "italian": "guardare",
    "german": "schauen / ansehen",
    "english": "to look at / to watch",
    "symbol": "👀",
    "sentence_es": "**Miro** las estrellas por la noche.",
    "sentence_it": "**Guardo** le stelle di notte.",
    "sentence_de": "Ich **schaue** nachts die Sterne **an**.",
    "sentence_en": "I **watch** the stars at night."
  },
  {
    "spanish": "empezar",
    "type": "verb",
    "gender": "-",
    "italian": "cominciare",
    "german": "anfangen / beginnen",
    "english": "to begin / to start",
    "symbol": "▶️",
    "sentence_es": "La clase **empieza** a las diez.",
    "sentence_it": "La lezione **comincia** alle dieci.",
    "sentence_de": "Der Unterricht **beginnt** um zehn Uhr.",
    "sentence_en": "The class **begins** at ten."
  },
  {
    "spanish": "volver",
    "type": "verb",
    "gender": "-",
    "italian": "tornare",
    "german": "zurückkehren",
    "english": "to return / to come back",
    "symbol": "🔄",
    "sentence_es": "**Vuelvo** a casa mañana.",
    "sentence_it": "**Torno** a casa domani.",
    "sentence_de": "Ich **kehre** morgen nach Hause **zurück**.",
    "sentence_en": "I **return** home tomorrow."
  },
  {
    "spanish": "dejar",
    "type": "verb",
    "gender": "-",
    "italian": "lasciare",
    "german": "lassen / verlassen",
    "english": "to leave / to let",
    "symbol": "👋",
    "sentence_es": "**Dejo** el libro en la mesa.",
    "sentence_it": "**Lascio** il libro sul tavolo.",
    "sentence_de": "Ich **lasse** das Buch auf dem Tisch.",
    "sentence_en": "I **leave** the book on the table."
  },
  {
    "spanish": "llevar",
    "type": "verb",
    "gender": "-",
    "italian": "portare",
    "german": "tragen / mitnehmen",
    "english": "to carry / to bring / to wear",
    "symbol": "🎒",
    "sentence_es": "**Llevo** una chaqueta roja.",
    "sentence_it": "**Porto** una giacca rossa.",
    "sentence_de": "Ich **trage** eine rote Jacke.",
    "sentence_en": "I **wear** a red jacket."
  },
  {
    "spanish": "pedir",
    "type": "verb",
    "gender": "-",
    "italian": "chiedere",
    "german": "bitten um / bestellen",
    "english": "to ask for / to order",
    "symbol": "🛎️",
    "sentence_es": "**Pido** un café con leche.",
    "sentence_it": "**Chiedo** un caffè con latte.",
    "sentence_de": "Ich **bestelle** einen Kaffee mit Milch.",
    "sentence_en": "I **order** a coffee with milk."
  },
  {
    "spanish": "preguntar",
    "type": "verb",
    "gender": "-",
    "italian": "domandare",
    "german": "fragen",
    "english": "to ask (a question)",
    "symbol": "❓",
    "sentence_es": "Le **pregunto** la hora.",
    "sentence_it": "Gli **domando** l'ora.",
    "sentence_de": "Ich **frage** ihn nach der Uhrzeit.",
    "sentence_en": "I **ask** him for the time."
  },
  {
    "spanish": "contestar",
    "type": "verb",
    "gender": "-",
    "italian": "rispondere",
    "german": "antworten",
    "english": "to answer",
    "symbol": "💬",
    "sentence_es": "**Contesto** la pregunta rápido.",
    "sentence_it": "**Rispondo** alla domanda velocemente.",
    "sentence_de": "Ich **antworte** schnell auf die Frage.",
    "sentence_en": "I **answer** the question quickly."
  },
  {
    "spanish": "intentar",
    "type": "verb",
    "gender": "-",
    "italian": "provare",
    "german": "versuchen",
    "english": "to try / to attempt",
    "symbol": "🎯",
    "sentence_es": "**Intento** aprender italiano.",
    "sentence_it": "**Provo** a imparare l'italiano.",
    "sentence_de": "Ich **versuche**, Italienisch zu lernen.",
    "sentence_en": "I **try** to learn Italian."
  },
  {
    "spanish": "aprender",
    "type": "verb",
    "gender": "-",
    "italian": "imparare",
    "german": "lernen",
    "english": "to learn",
    "symbol": "📖",
    "sentence_es": "**Aprendo** una lengua nueva.",
    "sentence_it": "**Imparo** una lingua nuova.",
    "sentence_de": "Ich **lerne** eine neue Sprache.",
    "sentence_en": "I **learn** a new language."
  },
  {
    "spanish": "enseñar",
    "type": "verb",
    "gender": "-",
    "italian": "insegnare",
    "german": "lehren / beibringen / zeigen",
    "english": "to teach / to show",
    "symbol": "🧑‍🏫",
    "sentence_es": "Ella **enseña** matemáticas.",
    "sentence_it": "Lei **insegna** matematica.",
    "sentence_de": "Sie **lehrt** Mathematik.",
    "sentence_en": "She **teaches** mathematics."
  },
  {
    "spanish": "elegir",
    "type": "verb",
    "gender": "-",
    "italian": "scegliere",
    "german": "auswählen / wählen",
    "english": "to choose / to select",
    "symbol": "👉",
    "sentence_es": "**Elijo** el vestido azul.",
    "sentence_it": "**Scelgo** il vestito blu.",
    "sentence_de": "Ich **wähle** das blaue Kleid.",
    "sentence_en": "I **choose** the blue dress."
  },
  {
    "spanish": "añadir",
    "type": "verb",
    "gender": "-",
    "italian": "aggiungere",
    "german": "hinzufügen",
    "english": "to add",
    "symbol": "➕",
    "sentence_es": "**Añado** sal a la sopa.",
    "sentence_it": "**Aggiungo** sale alla zuppa.",
    "sentence_de": "Ich **füge** der Suppe Salz **hinzu**.",
    "sentence_en": "I **add** salt to the soup."
  },
  {
    "spanish": "parar",
    "type": "verb",
    "gender": "-",
    "italian": "fermarsi",
    "german": "anhalten / stoppen",
    "english": "to stop",
    "symbol": "🛑",
    "sentence_es": "El autobús **para** aquí.",
    "sentence_it": "L'autobus si **ferma** qui.",
    "sentence_de": "Der Bus **hält** hier **an**.",
    "sentence_en": "The bus **stops** here."
  },
  {
    "spanish": "despertar",
    "type": "verb",
    "gender": "-",
    "italian": "svegliare",
    "german": "aufwecken",
    "english": "to wake up",
    "symbol": "⏰",
    "sentence_es": "**Despierto** a mi hermano temprano.",
    "sentence_it": "**Sveglio** mio fratello presto.",
    "sentence_de": "Ich **wecke** meinen Bruder früh **auf**.",
    "sentence_en": "I **wake** my brother up early."
  },
  {
    "spanish": "acostar",
    "type": "verb",
    "gender": "-",
    "italian": "coricare",
    "german": "zu Bett bringen / schlafen legen",
    "english": "to put to bed / lie down",
    "symbol": "🛌",
    "sentence_es": "**Acuesto** al bebé a las ocho.",
    "sentence_it": "**Corico** il bambino alle otto.",
    "sentence_de": "Ich **bringe** das Baby um acht Uhr **zu Bett**.",
    "sentence_en": "I **put** the baby **to bed** at eight."
  },
  {
    "spanish": "levantar",
    "type": "verb",
    "gender": "-",
    "italian": "alzare",
    "german": "aufheben / erheben",
    "english": "to lift / to raise",
    "symbol": "🏋️",
    "sentence_es": "**Levanto** la mano para preguntar.",
    "sentence_it": "**Alzo** la mano per chiedere.",
    "sentence_de": "Ich **hebe** die Hand, um zu fragen.",
    "sentence_en": "I **raise** my hand to ask."
  },
  {
    "spanish": "cuidar",
    "type": "verb",
    "gender": "-",
    "italian": "badare",
    "german": "sich kümmern um / pflegen",
    "english": "to take care of / to look after",
    "symbol": "🪴",
    "sentence_es": "**Cuido** a mi abuela los fines de semana.",
    "sentence_it": "**Bado** a mia nonna nei fine settimana.",
    "sentence_de": "Ich **kümmere mich** am Wochenende **um** meine Großmutter.",
    "sentence_en": "I **take care of** my grandmother on weekends."
  },
  {
    "spanish": "tirar",
    "type": "verb",
    "gender": "-",
    "italian": "buttare",
    "german": "werfen / wegwerfen",
    "english": "to throw / to throw away",
    "symbol": "🗑️",
    "sentence_es": "**Tiro** la basura todos los días.",
    "sentence_it": "**Butto** la spazzatura ogni giorno.",
    "sentence_de": "Ich **werfe** jeden Tag den Müll **weg**.",
    "sentence_en": "I **throw away** the trash every day."
  },
  {
    "spanish": "echar",
    "type": "verb",
    "gender": "-",
    "italian": "gettare",
    "german": "werfen / schütten / gießen",
    "english": "to throw / to pour / to put",
    "symbol": "🫗",
    "sentence_es": "**Echo** azúcar en el café.",
    "sentence_it": "**Getto** lo zucchero nel caffè.",
    "sentence_de": "Ich **schütte** Zucker in den Kaffee.",
    "sentence_en": "I **pour** sugar into the coffee."
  },
  {
    "spanish": "coger",
    "type": "verb",
    "gender": "-",
    "italian": "prendere",
    "german": "nehmen / greifen",
    "english": "to take / to grab",
    "symbol": "🤲",
    "sentence_es": "**Cojo** el autobús cada mañana.",
    "sentence_it": "**Prendo** l'autobus ogni mattina.",
    "sentence_de": "Ich **nehme** jeden Morgen den Bus.",
    "sentence_en": "I **take** the bus every morning."
  },
  {
    "spanish": "agarrar",
    "type": "verb",
    "gender": "-",
    "italian": "afferrare",
    "german": "packen / festhalten",
    "english": "to grab / to grasp",
    "symbol": "✊",
    "sentence_es": "**Agarro** la barra con fuerza.",
    "sentence_it": "**Afferro** la sbarra con forza.",
    "sentence_de": "Ich **packe** die Stange fest.",
    "sentence_en": "I **grab** the bar firmly."
  },
  {
    "spanish": "soltar",
    "type": "verb",
    "gender": "-",
    "italian": "rilasciare",
    "german": "loslassen",
    "english": "to let go / to release",
    "symbol": "👐",
    "sentence_es": "**Suelto** la cuerda poco a poco.",
    "sentence_it": "**Rilascio** la corda a poco a poco.",
    "sentence_de": "Ich **lasse** das Seil langsam **los**.",
    "sentence_en": "I **let go** of the rope slowly."
  },
  {
    "spanish": "apagar",
    "type": "verb",
    "gender": "-",
    "italian": "spegnere",
    "german": "ausschalten / löschen",
    "english": "to turn off / to extinguish",
    "symbol": "💡",
    "sentence_es": "**Apago** la luz antes de dormir.",
    "sentence_it": "**Spengo** la luce prima di dormire.",
    "sentence_de": "Ich **schalte** das Licht vor dem Schlafen **aus**.",
    "sentence_en": "I **turn off** the light before sleeping."
  },
  {
    "spanish": "encender",
    "type": "verb",
    "gender": "-",
    "italian": "accendere",
    "german": "einschalten / anzünden",
    "english": "to turn on / to light",
    "symbol": "🔥",
    "sentence_es": "**Enciendo** la televisión.",
    "sentence_it": "**Accendo** la televisione.",
    "sentence_de": "Ich **schalte** den Fernseher **ein**.",
    "sentence_en": "I **turn on** the television."
  },
  {
    "spanish": "esperar",
    "type": "verb",
    "gender": "-",
    "italian": "aspettare",
    "german": "warten",
    "english": "to wait / to expect",
    "symbol": "⏳",
    "sentence_es": "**Espero** el autobús en la parada.",
    "sentence_it": "**Aspetto** l'autobus alla fermata.",
    "sentence_de": "Ich **warte** an der Haltestelle auf den Bus.",
    "sentence_en": "I **wait** for the bus at the stop."
  },
  {
    "spanish": "parecer",
    "type": "verb",
    "gender": "-",
    "italian": "sembrare",
    "german": "scheinen / aussehen wie",
    "english": "to seem / to appear",
    "symbol": "👥",
    "sentence_es": "Ella **parece** cansada hoy.",
    "sentence_it": "Lei **sembra** stanca oggi.",
    "sentence_de": "Sie **scheint** heute müde zu sein.",
    "sentence_en": "She **seems** tired today."
  },
  {
    "spanish": "entender",
    "type": "verb",
    "gender": "-",
    "italian": "capire",
    "german": "verstehen",
    "english": "to understand",
    "symbol": "💡",
    "sentence_es": "No **entiendo** esta pregunta.",
    "sentence_it": "Non **capisco** questa domanda.",
    "sentence_de": "Ich **verstehe** diese Frage nicht.",
    "sentence_en": "I don't **understand** this question."
  },
  {
    "spanish": "dibujar",
    "type": "verb",
    "gender": "-",
    "italian": "disegnare",
    "german": "zeichnen",
    "english": "to draw",
    "symbol": "🎨",
    "sentence_es": "El niño **dibuja** un sol.",
    "sentence_it": "Il bambino **disegna** un sole.",
    "sentence_de": "Das Kind **zeichnet** eine Sonne.",
    "sentence_en": "The child **draws** a sun."
  },
  {
    "spanish": "burlar",
    "type": "verb",
    "gender": "-",
    "italian": "beffare",
    "german": "verspotten / foppen",
    "english": "to mock / to ridicule",
    "symbol": "😜",
    "sentence_es": "No debes **burlarte** de los demás.",
    "sentence_it": "Non devi **beffarti** degli altri.",
    "sentence_de": "Du solltest andere nicht **verspotten**.",
    "sentence_en": "You shouldn't **mock** others."
  },
  {
    "spanish": "despachar",
    "type": "verb",
    "gender": "-",
    "italian": "sbrigare",
    "german": "abfertigen / erledigen",
    "english": "to dispatch / to handle",
    "symbol": "📦",
    "sentence_es": "El empleado **despacha** el pedido rápido.",
    "sentence_it": "L'impiegato **sbriga** l'ordine velocemente.",
    "sentence_de": "Der Angestellte **erledigt** die Bestellung schnell.",
    "sentence_en": "The employee **handles** the order quickly."
  },
  {
    "spanish": "gastar",
    "type": "verb",
    "gender": "-",
    "italian": "spendere",
    "german": "ausgeben (Geld) / verbrauchen",
    "english": "to spend / to consume",
    "symbol": "💸",
    "sentence_es": "**Gasto** poco dinero en ropa.",
    "sentence_it": "**Spendo** poco denaro in vestiti.",
    "sentence_de": "Ich **gebe** wenig Geld für Kleidung **aus**.",
    "sentence_en": "I **spend** little money on clothes."
  },
  {
    "spanish": "ahorrar",
    "type": "verb",
    "gender": "-",
    "italian": "risparmiare",
    "german": "sparen",
    "english": "to save (money/energy)",
    "symbol": "💰",
    "sentence_es": "**Ahorro** dinero cada mes.",
    "sentence_it": "**Risparmio** denaro ogni mese.",
    "sentence_de": "Ich **spare** jeden Monat Geld.",
    "sentence_en": "I **save** money every month."
  },
  {
    "spanish": "arreglar",
    "type": "verb",
    "gender": "-",
    "italian": "riparare",
    "german": "reparieren / in Ordnung bringen",
    "english": "to fix / to arrange",
    "symbol": "🔧",
    "sentence_es": "**Arreglo** la bicicleta rota.",
    "sentence_it": "**Riparo** la bicicletta rotta.",
    "sentence_de": "Ich **repariere** das kaputte Fahrrad.",
    "sentence_en": "I **fix** the broken bicycle."
  },
  {
    "spanish": "alquilar",
    "type": "verb",
    "gender": "-",
    "italian": "affittare",
    "german": "mieten / vermieten",
    "english": "to rent / to hire",
    "symbol": "🔑",
    "sentence_es": "**Alquilamos** un piso en el centro.",
    "sentence_it": "**Affittiamo** un appartamento in centro.",
    "sentence_de": "Wir **mieten** eine Wohnung im Zentrum.",
    "sentence_en": "We **rent** an apartment downtown."
  },
  {
    "spanish": "lograr",
    "type": "verb",
    "gender": "-",
    "italian": "raggiungere",
    "german": "schaffen / erreichen",
    "english": "to achieve / to manage to",
    "symbol": "🏆",
    "sentence_es": "Por fin **logro** mi objetivo.",
    "sentence_it": "Finalmente **raggiungo** il mio obiettivo.",
    "sentence_de": "Endlich **erreiche** ich mein Ziel.",
    "sentence_en": "I finally **achieve** my goal."
  },
  {
    "spanish": "quejarse",
    "type": "verb",
    "gender": "-",
    "italian": "lamentarsi",
    "german": "sich beschweren / klagen",
    "english": "to complain",
    "symbol": "😤",
    "sentence_es": "Siempre se **queja** del tiempo.",
    "sentence_it": "Si **lamenta** sempre del tempo.",
    "sentence_de": "Er **beschwert sich** immer über das Wetter.",
    "sentence_en": "He always **complains** about the weather."
  },
  {
    "spanish": "apoyar",
    "type": "verb",
    "gender": "-",
    "italian": "sostenere",
    "german": "unterstützen / stützen",
    "english": "to support / to lean",
    "symbol": "🤝",
    "sentence_es": "**Apoyo** a mi equipo siempre.",
    "sentence_it": "**Sostengo** sempre la mia squadra.",
    "sentence_de": "Ich **unterstütze** immer mein Team.",
    "sentence_en": "I always **support** my team."
  },
  {
    "spanish": "borrar",
    "type": "verb",
    "gender": "-",
    "italian": "cancellare",
    "german": "löschen / ausradieren",
    "english": "to erase / to delete",
    "symbol": "🧹",
    "sentence_es": "**Borro** el error con la goma.",
    "sentence_it": "**Cancello** l'errore con la gomma.",
    "sentence_de": "Ich **radiere** den Fehler mit dem Radiergummi **aus**.",
    "sentence_en": "I **erase** the mistake with the eraser."
  },
  {
    "spanish": "chocar",
    "type": "verb",
    "gender": "-",
    "italian": "urtare",
    "german": "zusammenstoßen / kollidieren",
    "english": "to crash / to collide",
    "symbol": "💥",
    "sentence_es": "El coche **choca** contra el árbol.",
    "sentence_it": "L'auto **urta** contro l'albero.",
    "sentence_de": "Das Auto **kollidiert** mit dem Baum.",
    "sentence_en": "The car **crashes** into the tree."
  },
  {
    "spanish": "rebanar",
    "type": "verb",
    "gender": "-",
    "italian": "affettare",
    "german": "in Scheiben schneiden",
    "english": "to slice",
    "symbol": "🔪",
    "sentence_es": "**Rebano** el pan para el desayuno.",
    "sentence_it": "**Affetto** il pane per la colazione.",
    "sentence_de": "Ich **schneide** das Brot für das Frühstück **in Scheiben**.",
    "sentence_en": "I **slice** the bread for breakfast."
  },
  {
    "spanish": "derramar",
    "type": "verb",
    "gender": "-",
    "italian": "rovesciare",
    "german": "verschütten / vergießen",
    "english": "to spill",
    "symbol": "🫗",
    "sentence_es": "**Derramo** el café sobre la mesa.",
    "sentence_it": "**Rovescio** il caffè sul tavolo.",
    "sentence_de": "Ich **verschütte** den Kaffee auf dem Tisch.",
    "sentence_en": "I **spill** the coffee on the table."
  },
  {
    "spanish": "empujar",
    "type": "verb",
    "gender": "-",
    "italian": "spingere",
    "german": "schieben / stoßen",
    "english": "to push",
    "symbol": "👐",
    "sentence_es": "**Empujo** la puerta para abrirla.",
    "sentence_it": "**Spingo** la porta per aprirla.",
    "sentence_de": "Ich **schiebe** die Tür, um sie zu öffnen.",
    "sentence_en": "I **push** the door to open it."
  },
  {
    "spanish": "jalar",
    "type": "verb",
    "gender": "-",
    "italian": "tirare",
    "german": "ziehen",
    "english": "to pull",
    "symbol": "🧗",
    "sentence_es": "**Jalo** la cuerda con fuerza.",
    "sentence_it": "**Tiro** la corda con forza.",
    "sentence_de": "Ich **ziehe** das Seil fest.",
    "sentence_en": "I **pull** the rope hard."
  },
  {
    "spanish": "golpear",
    "type": "verb",
    "gender": "-",
    "italian": "picchiare",
    "german": "schlagen / treffen",
    "english": "to hit / to strike",
    "symbol": "🥊",
    "sentence_es": "No debes **golpear** a nadie.",
    "sentence_it": "Non devi **picchiare** nessuno.",
    "sentence_de": "Du sollst niemanden **schlagen**.",
    "sentence_en": "You shouldn't **hit** anyone."
  },
  {
    "spanish": "rechazar",
    "type": "verb",
    "gender": "-",
    "italian": "rifiutare",
    "german": "ablehnen / zurückweisen",
    "english": "to reject / to refuse",
    "symbol": "🚫",
    "sentence_es": "**Rechazo** esa oferta injusta.",
    "sentence_it": "**Rifiuto** quell'offerta ingiusta.",
    "sentence_de": "Ich **lehne** dieses unfaire Angebot **ab**.",
    "sentence_en": "I **reject** that unfair offer."
  },
  {
    "spanish": "entregar",
    "type": "verb",
    "gender": "-",
    "italian": "consegnare",
    "german": "übergeben / abliefern",
    "english": "to deliver / to hand over",
    "symbol": "🎁",
    "sentence_es": "**Entrego** el paquete a tiempo.",
    "sentence_it": "**Consegno** il pacco in tempo.",
    "sentence_de": "Ich **liefere** das Paket pünktlich **ab**.",
    "sentence_en": "I **deliver** the package on time."
  },
  {
    "spanish": "madrugar",
    "type": "verb",
    "gender": "-",
    "italian": "alzarsi presto",
    "german": "früh aufstehen",
    "english": "to wake up early",
    "symbol": "🌄",
    "sentence_es": "Mañana tengo que **madrugar**.",
    "sentence_it": "Domani devo **alzarmi presto**.",
    "sentence_de": "Morgen muss ich **früh aufstehen**.",
    "sentence_en": "Tomorrow I have to **wake up early**."
  },
  {
    "spanish": "rojo",
    "type": "adjective",
    "gender": "-",
    "italian": "rosso",
    "german": "rot",
    "english": "red",
    "symbol": "🔴",
    "sentence_es": "El vestido es **rojo**.",
    "sentence_it": "Il vestito è **rosso**.",
    "sentence_de": "Das Kleid ist **rot**.",
    "sentence_en": "The dress is **red**."
  },
  {
    "spanish": "amarillo",
    "type": "adjective",
    "gender": "-",
    "italian": "giallo",
    "german": "gelb",
    "english": "yellow",
    "symbol": "🟡",
    "sentence_es": "El sol es **amarillo**.",
    "sentence_it": "Il sole è **giallo**.",
    "sentence_de": "Die Sonne ist **gelb**.",
    "sentence_en": "The sun is **yellow**."
  },
  {
    "spanish": "pequeño",
    "type": "adjective",
    "gender": "-",
    "italian": "piccolo",
    "german": "klein",
    "english": "small / little",
    "symbol": "🤏",
    "sentence_es": "El perro es muy **pequeño**.",
    "sentence_it": "Il cane è molto **piccolo**.",
    "sentence_de": "Der Hund ist sehr **klein**.",
    "sentence_en": "The dog is very **small**."
  },
  {
    "spanish": "ancho",
    "type": "adjective",
    "gender": "-",
    "italian": "largo",
    "german": "breit / weit",
    "english": "wide / broad",
    "symbol": "↔️",
    "sentence_es": "El río es muy **ancho**.",
    "sentence_it": "Il fiume è molto **largo**.",
    "sentence_de": "Der Fluss ist sehr **breit**.",
    "sentence_en": "The river is very **wide**."
  },
  {
    "spanish": "estrecho",
    "type": "adjective",
    "gender": "-",
    "italian": "stretto",
    "german": "eng / schmal",
    "english": "narrow",
    "symbol": "⏸️",
    "sentence_es": "La calle es muy **estrecha**.",
    "sentence_it": "La strada è molto **stretta**.",
    "sentence_de": "Die Straße ist sehr **eng**.",
    "sentence_en": "The street is very **narrow**."
  },
  {
    "spanish": "delgado",
    "type": "adjective",
    "gender": "-",
    "italian": "magro",
    "german": "dünn / schlank",
    "english": "thin / slender",
    "symbol": "🪡",
    "sentence_es": "Mi hermano es muy **delgado**.",
    "sentence_it": "Mio fratello è molto **magro**.",
    "sentence_de": "Mein Bruder ist sehr **schlank**.",
    "sentence_en": "My brother is very **thin**."
  },
  {
    "spanish": "gordo",
    "type": "adjective",
    "gender": "-",
    "italian": "grasso",
    "german": "dick / fett",
    "english": "fat",
    "symbol": "🐘",
    "sentence_es": "El gato está muy **gordo**.",
    "sentence_it": "Il gatto è molto **grasso**.",
    "sentence_de": "Die Katze ist sehr **dick**.",
    "sentence_en": "The cat is very **fat**."
  },
  {
    "spanish": "blando",
    "type": "adjective",
    "gender": "-",
    "italian": "morbido",
    "german": "weich",
    "english": "soft",
    "symbol": "🪶",
    "sentence_es": "Este colchón es muy **blando**.",
    "sentence_it": "Questo materasso è molto **morbido**.",
    "sentence_de": "Diese Matratze ist sehr **weich**.",
    "sentence_en": "This mattress is very **soft**."
  },
  {
    "spanish": "limpio",
    "type": "adjective",
    "gender": "-",
    "italian": "pulito",
    "german": "sauber",
    "english": "clean",
    "symbol": "✨",
    "sentence_es": "El suelo está **limpio**.",
    "sentence_it": "Il pavimento è **pulito**.",
    "sentence_de": "Der Boden ist **sauber**.",
    "sentence_en": "The floor is **clean**."
  },
  {
    "spanish": "sucio",
    "type": "adjective",
    "gender": "-",
    "italian": "sporco",
    "german": "schmutzig / dreckig",
    "english": "dirty",
    "symbol": "💩",
    "sentence_es": "Tu camisa está **sucia**.",
    "sentence_it": "La tua camicia è **sporca**.",
    "sentence_de": "Dein Hemd ist **schmutzig**.",
    "sentence_en": "Your shirt is **dirty**."
  },
  {
    "spanish": "listo",
    "type": "adjective",
    "gender": "-",
    "italian": "furbo",
    "german": "schlau / bereit",
    "english": "clever / ready",
    "symbol": "🧠",
    "sentence_es": "Ese niño es muy **listo**.",
    "sentence_it": "Quel bambino è molto **furbo**.",
    "sentence_de": "Dieses Kind ist sehr **schlau**.",
    "sentence_en": "That child is very **clever**."
  },
  {
    "spanish": "tonto",
    "type": "adjective",
    "gender": "-",
    "italian": "sciocco",
    "german": "dumm / albern",
    "english": "silly / foolish",
    "symbol": "🤡",
    "sentence_es": "No seas **tonto**.",
    "sentence_it": "Non essere **sciocco**.",
    "sentence_de": "Sei nicht **dumm**.",
    "sentence_en": "Don't be **silly**."
  },
  {
    "spanish": "guapo",
    "type": "adjective",
    "gender": "-",
    "italian": "bello",
    "german": "hübsch / gutaussehend",
    "english": "handsome / good-looking",
    "symbol": "✨",
    "sentence_es": "Tu novio es muy **guapo**.",
    "sentence_it": "Il tuo ragazzo è molto **bello**.",
    "sentence_de": "Dein Freund ist sehr **gutaussehend**.",
    "sentence_en": "Your boyfriend is very **handsome**."
  },
  {
    "spanish": "feo",
    "type": "adjective",
    "gender": "-",
    "italian": "brutto",
    "german": "hässlich",
    "english": "ugly",
    "symbol": "👺",
    "sentence_es": "Ese edificio es muy **feo**.",
    "sentence_it": "Quell'edificio è molto **brutto**.",
    "sentence_de": "Dieses Gebäude ist sehr **hässlich**.",
    "sentence_en": "That building is very **ugly**."
  },
  {
    "spanish": "viejo",
    "type": "adjective",
    "gender": "-",
    "italian": "vecchio",
    "german": "alt",
    "english": "old",
    "symbol": "👴",
    "sentence_es": "Mi abuelo es **viejo** pero fuerte.",
    "sentence_it": "Mio nonno è **vecchio** ma forte.",
    "sentence_de": "Mein Großvater ist **alt**, aber stark.",
    "sentence_en": "My grandfather is **old** but strong."
  },
  {
    "spanish": "caliente",
    "type": "adjective",
    "gender": "-",
    "italian": "caldo",
    "german": "heiß / warm",
    "english": "hot / warm",
    "symbol": "🔥",
    "sentence_es": "El café está muy **caliente**.",
    "sentence_it": "Il caffè è molto **caldo**.",
    "sentence_de": "Der Kaffee ist sehr **heiß**.",
    "sentence_en": "The coffee is very **hot**."
  },
  {
    "spanish": "agrio",
    "type": "adjective",
    "gender": "-",
    "italian": "aspro",
    "german": "sauer",
    "english": "sour",
    "symbol": "🍋",
    "sentence_es": "Este limón está muy **agrio**.",
    "sentence_it": "Questo limone è molto **aspro**.",
    "sentence_de": "Diese Zitrone ist sehr **sauer**.",
    "sentence_en": "This lemon is very **sour**."
  },
  {
    "spanish": "sabroso",
    "type": "adjective",
    "gender": "-",
    "italian": "saporito",
    "german": "schmackhaft / lecker",
    "english": "tasty / flavorful",
    "symbol": "😋",
    "sentence_es": "La comida está muy **sabrosa**.",
    "sentence_it": "Il cibo è molto **saporito**.",
    "sentence_de": "Das Essen ist sehr **lecker**.",
    "sentence_en": "The food is very **tasty**."
  },
  {
    "spanish": "barato",
    "type": "adjective",
    "gender": "-",
    "italian": "economico",
    "german": "billig / günstig",
    "english": "cheap / inexpensive",
    "symbol": "🏷️",
    "sentence_es": "Este hotel es muy **barato**.",
    "sentence_it": "Questo hotel è molto **economico**.",
    "sentence_de": "Dieses Hotel ist sehr **günstig**.",
    "sentence_en": "This hotel is very **cheap**."
  },
  {
    "spanish": "lleno",
    "type": "adjective",
    "gender": "-",
    "italian": "pieno",
    "german": "voll",
    "english": "full",
    "symbol": "🌕",
    "sentence_es": "El vaso está **lleno** de agua.",
    "sentence_it": "Il bicchiere è **pieno** d'acqua.",
    "sentence_de": "Das Glas ist **voll** mit Wasser.",
    "sentence_en": "The glass is **full** of water."
  },
  {
    "spanish": "vacío",
    "type": "adjective",
    "gender": "-",
    "italian": "vuoto",
    "german": "leer",
    "english": "empty",
    "symbol": "⭕",
    "sentence_es": "La botella está **vacía**.",
    "sentence_it": "La bottiglia è **vuota**.",
    "sentence_de": "Die Flasche ist **leer**.",
    "sentence_en": "The bottle is **empty**."
  },
  {
    "spanish": "lejos",
    "type": "adverb",
    "gender": "-",
    "italian": "lontano",
    "german": "weit / fern",
    "english": "far away",
    "symbol": "",
    "sentence_es": "Vivo muy **lejos** del centro.",
    "sentence_it": "Vivo molto **lontano** dal centro.",
    "sentence_de": "Ich wohne sehr **weit** vom Zentrum entfernt.",
    "sentence_en": "I live very **far** from downtown."
  },
  {
    "spanish": "cerca",
    "type": "adverb",
    "gender": "-",
    "italian": "vicino",
    "german": "nah / in der Nähe",
    "english": "close / near",
    "symbol": "",
    "sentence_es": "La tienda está **cerca** de casa.",
    "sentence_it": "Il negozio è **vicino** a casa.",
    "sentence_de": "Der Laden ist **nah** bei meinem Haus.",
    "sentence_en": "The store is **close** to home."
  },
  {
    "spanish": "despacio",
    "type": "adverb",
    "gender": "-",
    "italian": "piano",
    "german": "langsam",
    "english": "slowly",
    "symbol": "",
    "sentence_es": "Conduce más **despacio**, por favor.",
    "sentence_it": "Guida più **piano**, per favore.",
    "sentence_de": "Fahr bitte **langsamer**.",
    "sentence_en": "Drive more **slowly**, please."
  },
  {
    "spanish": "deprisa",
    "type": "adverb",
    "gender": "-",
    "italian": "in fretta",
    "german": "schnell / eilig",
    "english": "quickly / hurriedly",
    "symbol": "",
    "sentence_es": "Comimos **deprisa** porque teníamos prisa.",
    "sentence_it": "Abbiamo mangiato **in fretta** perché avevamo fretta.",
    "sentence_de": "Wir aßen **schnell**, weil wir es eilig hatten.",
    "sentence_en": "We ate **quickly** because we were in a hurry."
  },
  {
    "spanish": "temprano",
    "type": "adverb",
    "gender": "-",
    "italian": "presto",
    "german": "früh",
    "english": "early",
    "symbol": "",
    "sentence_es": "Me levanto **temprano** cada día.",
    "sentence_it": "Mi alzo **presto** ogni giorno.",
    "sentence_de": "Ich stehe jeden Tag **früh** auf.",
    "sentence_en": "I get up **early** every day."
  },
  {
    "spanish": "enseguida",
    "type": "adverb",
    "gender": "-",
    "italian": "subito",
    "german": "sofort / auf der Stelle",
    "english": "immediately / right away",
    "symbol": "",
    "sentence_es": "Vuelvo **enseguida**, espérame.",
    "sentence_it": "Torno **subito**, aspettami.",
    "sentence_de": "Ich komme **sofort** zurück, warte auf mich.",
    "sentence_en": "I'll be back **immediately**, wait for me."
  },
  {
    "spanish": "ahora",
    "type": "adverb",
    "gender": "-",
    "italian": "adesso",
    "german": "jetzt",
    "english": "now",
    "symbol": "",
    "sentence_es": "**Ahora** no puedo hablar.",
    "sentence_it": "**Adesso** non posso parlare.",
    "sentence_de": "**Jetzt** kann ich nicht sprechen.",
    "sentence_en": "I can't talk **now**."
  },
  {
    "spanish": "todavía",
    "type": "adverb",
    "gender": "-",
    "italian": "ancora",
    "german": "noch",
    "english": "still / yet",
    "symbol": "",
    "sentence_es": "**Todavía** no he terminado.",
    "sentence_it": "Non ho **ancora** finito.",
    "sentence_de": "Ich bin **noch** nicht fertig.",
    "sentence_en": "I haven't finished **yet**."
  },
  {
    "spanish": "nunca",
    "type": "adverb",
    "gender": "-",
    "italian": "mai",
    "german": "nie / niemals",
    "english": "never",
    "symbol": "",
    "sentence_es": "**Nunca** como carne.",
    "sentence_it": "Non mangio **mai** carne.",
    "sentence_de": "Ich esse **nie** Fleisch.",
    "sentence_en": "I **never** eat meat."
  },
  {
    "spanish": "jamás",
    "type": "adverb",
    "gender": "-",
    "italian": "mai",
    "german": "jemals / nie",
    "english": "never / ever",
    "symbol": "",
    "sentence_es": "**Jamás** he visto algo así.",
    "sentence_it": "Non ho **mai** visto una cosa simile.",
    "sentence_de": "Ich habe so etwas **nie** gesehen.",
    "sentence_en": "I have **never** seen anything like this."
  },
  {
    "spanish": "a menudo",
    "type": "adverbial phrase",
    "gender": "-",
    "italian": "spesso",
    "german": "oft / häufig",
    "english": "often",
    "symbol": "",
    "sentence_es": "Voy **a menudo** al gimnasio.",
    "sentence_it": "Vado **spesso** in palestra.",
    "sentence_de": "Ich gehe **oft** ins Fitnessstudio.",
    "sentence_en": "I **often** go to the gym."
  },
  {
    "spanish": "a veces",
    "type": "adverbial phrase",
    "gender": "-",
    "italian": "a volte",
    "german": "manchmal",
    "english": "sometimes",
    "symbol": "",
    "sentence_es": "**A veces** llueve en verano.",
    "sentence_it": "**A volte** piove in estate.",
    "sentence_de": "**Manchmal** regnet es im Sommer.",
    "sentence_en": "**Sometimes** it rains in summer."
  },
  {
    "spanish": "quizás",
    "type": "adverb",
    "gender": "-",
    "italian": "forse",
    "german": "vielleicht",
    "english": "maybe / perhaps",
    "symbol": "",
    "sentence_es": "**Quizás** llueva mañana.",
    "sentence_it": "**Forse** domani piove.",
    "sentence_de": "**Vielleicht** regnet es morgen.",
    "sentence_en": "**Maybe** it will rain tomorrow."
  },
  {
    "spanish": "tal vez",
    "type": "adverbial phrase",
    "gender": "-",
    "italian": "forse",
    "german": "vielleicht",
    "english": "maybe / perhaps",
    "symbol": "",
    "sentence_es": "**Tal vez** venga a la fiesta.",
    "sentence_it": "**Forse** vengo alla festa.",
    "sentence_de": "**Vielleicht** komme ich zur Party.",
    "sentence_en": "**Maybe** I'll come to the party."
  },
  {
    "spanish": "arriba",
    "type": "adverb",
    "gender": "-",
    "italian": "su",
    "german": "oben / hinauf",
    "english": "up / upstairs / above",
    "symbol": "",
    "sentence_es": "Voy **arriba** a dormir.",
    "sentence_it": "Vado **su** a dormire.",
    "sentence_de": "Ich gehe **nach oben** schlafen.",
    "sentence_en": "I go **upstairs** to sleep."
  },
  {
    "spanish": "abajo",
    "type": "adverb",
    "gender": "-",
    "italian": "giù",
    "german": "unten / hinab",
    "english": "down / downstairs / below",
    "symbol": "",
    "sentence_es": "Voy **abajo** a la cocina.",
    "sentence_it": "Vado **giù** in cucina.",
    "sentence_de": "Ich gehe **nach unten** in die Küche.",
    "sentence_en": "I go **downstairs** to the kitchen."
  },
  {
    "spanish": "adelante",
    "type": "adverb",
    "gender": "-",
    "italian": "avanti",
    "german": "vorwärts / voran",
    "english": "forward / ahead",
    "symbol": "",
    "sentence_es": "Sigue **adelante**, no te detengas.",
    "sentence_it": "Vai **avanti**, non fermarti.",
    "sentence_de": "Geh **vorwärts**, hör nicht auf.",
    "sentence_en": "Keep going **forward**, don't stop."
  },
  {
    "spanish": "atrás",
    "type": "adverb",
    "gender": "-",
    "italian": "indietro",
    "german": "zurück / hinten",
    "english": "back / behind",
    "symbol": "",
    "sentence_es": "Da un paso hacia **atrás**.",
    "sentence_it": "Fai un passo **indietro**.",
    "sentence_de": "Mach einen Schritt nach **hinten**.",
    "sentence_en": "Take a step **back**."
  },
  {
    "spanish": "alrededor",
    "type": "adverb",
    "gender": "-",
    "italian": "intorno",
    "german": "herum / ringsum",
    "english": "around",
    "symbol": "",
    "sentence_es": "Los niños corren **alrededor** del árbol.",
    "sentence_it": "I bambini corrono **intorno** all'albero.",
    "sentence_de": "Die Kinder rennen **um** den Baum **herum**.",
    "sentence_en": "The children run **around** the tree."
  },
  {
    "spanish": "enfrente",
    "type": "adverb",
    "gender": "-",
    "italian": "di fronte",
    "german": "gegenüber",
    "english": "opposite / in front",
    "symbol": "",
    "sentence_es": "La panadería está **enfrente** de mi casa.",
    "sentence_it": "La panetteria è **di fronte** a casa mia.",
    "sentence_de": "Die Bäckerei liegt **gegenüber** meinem Haus.",
    "sentence_en": "The bakery is **opposite** my house."
  },
  {
    "spanish": "izquierda",
    "type": "noun / adjective",
    "gender": "feminine",
    "italian": "sinistra",
    "german": "links / linke Seite",
    "english": "left",
    "symbol": "⬅️",
    "sentence_es": "Gira a la **izquierda** en la esquina.",
    "sentence_it": "Gira a **sinistra** all'angolo.",
    "sentence_de": "Bieg an der Ecke nach **links** ab.",
    "sentence_en": "Turn **left** at the corner."
  },
  {
    "spanish": "derecha",
    "type": "noun / adjective",
    "gender": "feminine",
    "italian": "destra",
    "german": "rechts / rechte Seite",
    "english": "right",
    "symbol": "➡️",
    "sentence_es": "Gira a la **derecha** en el semáforo.",
    "sentence_it": "Gira a **destra** al semaforo.",
    "sentence_de": "Bieg an der Ampel nach **rechts** ab.",
    "sentence_en": "Turn **right** at the traffic light."
  },
  {
    "spanish": "demasiado",
    "type": "adverb / adjective",
    "gender": "-",
    "italian": "troppo",
    "german": "zu / zu viel",
    "english": "too / too much",
    "symbol": "📈",
    "sentence_es": "Comes **demasiado** rápido.",
    "sentence_it": "Mangi **troppo** velocemente.",
    "sentence_de": "Du isst **zu** schnell.",
    "sentence_en": "You eat **too** fast."
  },
  {
    "spanish": "bastante",
    "type": "adverb / adjective",
    "gender": "-",
    "italian": "abbastanza",
    "german": "ziemlich / genug",
    "english": "quite / enough",
    "symbol": "👍",
    "sentence_es": "Estoy **bastante** cansado hoy.",
    "sentence_it": "Sono **abbastanza** stanco oggi.",
    "sentence_de": "Ich bin heute **ziemlich** müde.",
    "sentence_en": "I am **quite** tired today."
  },
  {
    "spanish": "igual",
    "type": "adjective / adverb",
    "gender": "-",
    "italian": "uguale",
    "german": "gleich",
    "english": "equal / same",
    "symbol": "🟰",
    "sentence_es": "Los dos vestidos son **iguales**.",
    "sentence_it": "I due vestiti sono **uguali**.",
    "sentence_de": "Die beiden Kleider sind **gleich**.",
    "sentence_en": "The two dresses are the **same**."
  },
  {
    "spanish": "mismo",
    "type": "adjective / pronoun",
    "gender": "-",
    "italian": "stesso",
    "german": "selbe / gleiche",
    "english": "same",
    "symbol": "🪞",
    "sentence_es": "Tenemos el **mismo** problema.",
    "sentence_it": "Abbiamo lo **stesso** problema.",
    "sentence_de": "Wir haben das **gleiche** Problem.",
    "sentence_en": "We have the **same** problem."
  },
  {
    "spanish": "cada",
    "type": "determiner",
    "gender": "-",
    "italian": "ogni",
    "german": "jeder / jede / jedes",
    "english": "each / every",
    "symbol": "",
    "sentence_es": "**Cada** persona tiene su opinión.",
    "sentence_it": "**Ogni** persona ha la sua opinione.",
    "sentence_de": "**Jede** Person hat ihre Meinung.",
    "sentence_en": "**Every** person has their opinion."
  },
  {
    "spanish": "ambos",
    "type": "determiner / pronoun",
    "gender": "masculine (plural)",
    "italian": "entrambi",
    "german": "beide",
    "english": "both",
    "symbol": "",
    "sentence_es": "**Ambos** hermanos estudian medicina.",
    "sentence_it": "**Entrambi** i fratelli studiano medicina.",
    "sentence_de": "**Beide** Brüder studieren Medizin.",
    "sentence_en": "**Both** brothers study medicine."
  },
  {
    "spanish": "ninguno",
    "type": "determiner / pronoun",
    "gender": "masculine",
    "italian": "nessuno",
    "german": "keiner / niemand",
    "english": "none / no one",
    "symbol": "",
    "sentence_es": "**Ninguno** de los dos vino a la fiesta.",
    "sentence_it": "**Nessuno** dei due è venuto alla festa.",
    "sentence_de": "**Keiner** von beiden kam zur Party.",
    "sentence_en": "**None** of the two came to the party."
  },
  {
    "spanish": "alguien",
    "type": "pronoun",
    "gender": "-",
    "italian": "qualcuno",
    "german": "jemand",
    "english": "someone / somebody",
    "symbol": "",
    "sentence_es": "**Alguien** está tocando a la puerta.",
    "sentence_it": "**Qualcuno** sta bussando alla porta.",
    "sentence_de": "**Jemand** klopft an die Tür.",
    "sentence_en": "**Someone** is knocking at the door."
  },
  {
    "spanish": "nadie",
    "type": "pronoun",
    "gender": "-",
    "italian": "nessuno",
    "german": "niemand",
    "english": "nobody / no one",
    "symbol": "",
    "sentence_es": "**Nadie** contestó el teléfono.",
    "sentence_it": "**Nessuno** ha risposto al telefono.",
    "sentence_de": "**Niemand** hat ans Telefon geantwortet.",
    "sentence_en": "**Nobody** answered the phone."
  },
  {
    "spanish": "algo",
    "type": "pronoun",
    "gender": "-",
    "italian": "qualcosa",
    "german": "etwas",
    "english": "something / anything",
    "symbol": "",
    "sentence_es": "Quiero comer **algo** dulce.",
    "sentence_it": "Voglio mangiare **qualcosa** di dolce.",
    "sentence_de": "Ich möchte **etwas** Süßes essen.",
    "sentence_en": "I want to eat **something** sweet."
  },
  {
    "spanish": "nada",
    "type": "pronoun / adverb",
    "gender": "-",
    "italian": "niente",
    "german": "nichts",
    "english": "nothing / not at all",
    "symbol": "",
    "sentence_es": "No quiero **nada** más, gracias.",
    "sentence_it": "Non voglio **niente** altro, grazie.",
    "sentence_de": "Ich möchte **nichts** mehr, danke.",
    "sentence_en": "I want **nothing** else, thanks."
  },
  {
    "spanish": "pero",
    "type": "conjunction",
    "gender": "-",
    "italian": "ma",
    "german": "aber",
    "english": "but",
    "symbol": "",
    "sentence_es": "Quiero ir, **pero** no tengo tiempo.",
    "sentence_it": "Voglio andare, **ma** non ho tempo.",
    "sentence_de": "Ich möchte gehen, **aber** ich habe keine Zeit.",
    "sentence_en": "I want to go, **but** I don't have time."
  }
];
